### ISSUE TITLE
Estendere l'orario di apertura della Biblioteca

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#11]
Viene proposto un percorso graduale per estendere l'orario di apertura della Biblioteca, in modo da permettere un servizio maggiormente accessibile.

Attualmente questi sono gli orari:

<img width="244" alt="screen shot 2016-10-06 at 10 04 36" src="https://cloud.githubusercontent.com/assets/21038/19146215/dc871d8a-8bb2-11e6-8b0e-8c4876eaa47f.png">

I seguenti passaggi possono essere introdotti singolarmente, seguiti da un periodo di assestamento (ad esempio 1 settimana o 1 mese).
1. allungare la chiusura dalle 18:15 alle 19:00
2. aggiungere la domenica pomeriggio 14:00 - 19:00
3. un giorno la settimana (mercoledì?) fino alle 23, per permettere eventualmente incontri culturali

Si suggerisce un'eventuale sondaggio in modo da chiedere ai cittadini la priorità percepita da ogni singolo passaggio, in modo da tararli e introdurli al meglio.

A scopo d'esempio, qui gli orari applicati dalla Biblioteca "Il Pertini" di Cinisello Balsamo:

<img width="169" alt="screen shot 2016-10-06 at 10 05 52" src="https://cloud.githubusercontent.com/assets/21038/19146242/f96c2a9e-8bb2-11e6-9628-b9d24b4be580.png">

## Attività

- [x] richiesta di avvio di una discussione con Comune e Biblioteca
- [x] definizione della fattibilità (costi previsti)
- [x] eventuale raccolta di feedback da parte dei cittadini
- [x] definizione della strategia di modifica incrementale dell'orario di apertura della Biblioteca

**Comment by olistik** [comment]
inviata tramite PEC a protocollo.comune.desio@legalmail.it

> Buongiorno,
> 
> avanzo la proposta di estensione dell'orario di apertura della Biblioteca.
> 
> Ho inserito i dettagli della proposta in questo indirizzo:
> 
> https://github.com/open-comune/desio/issues/11
> 
> Vorrei chiedervi se è possibile instaurare un dialogo con il Comune e la Biblioteca in modo da definire la fattibilità di questa proposta.
> 
> Saluti

**Comment by emilianoferrari1** [comment]
A Cinisello viene pagata una cooperativa che fornisce personale in affiancamento a quello pubblico.
So che a Desio ci sono anche i volontari della biblioteca... sarebbe interessante sapere cosa gli hanno prospettato .... ;-)

**Comment by achitac** [comment]
Su questo tema ho avuto un incontro un mese fa con il direttore della biblioteca, presente l'Assessore Redi, proprio per vagliare le possibilità di estensione dell'orario di apertura.

Copio qui una relazione che avevo scritto di quell'incontro.

---

L’incontro serviva a sondare le possibilità di rivedere l’orario di apertura della biblioteca. Una modifica infatti sarebbe la naturale prosecuzione del percorso cominciato nel 2014 con un questionario sottoposto all’utenza, di cui vi allego i risultati, e passato poi per una sperimentazione trimestrale, durante l’estate 2015, che prevedeva il posticipo della chiusura serale di un giorno alla settimana alle 22.30 anziché alle 18.15. L’obiettivo di questo percorso è di avvicinare il servizio alle esigenze di tutte le sue categorie di utenti; una modifica dell’orario, diversa da quella attuata in sede di sperimentazione, si rende necessaria anche in seguito agli esiti negativi dati da quest’ultima, che in termini sia di presenze negli spazi della biblioteca sia di prestiti effettuati si è rivelata insoddisfacente.

Anzitutto, l’ostacolo principale all’estensione dell’orario di apertura del servizio è certamente la carenza di personale. Questo in biblioteca è ripartito in tre “categorie”:
- personale dipendente (a tempo pieno o part time),
- personale di cooperativa esterna,
- personale proveniente dal servizio civile nazionale.

Per quanto riguarda la prima categoria, il problema si è posto di recente, quando è stato “scoperto” che di lì a poco un dipendente sarebbe andato in pensione: stante l’impossibilità di nuove assunzioni, dovrà essere sostituita con una figura proveniente dalla mobilità provinciale, cosa che presumibilmente avverrà entro la fine dell’anno. Il personale di cooperativa invece si compone di due figure, una delle quali attualmente è in maternità, con l’altra che per ora copre le ore di entrambi. Il personale del servizio civile, infine, è molto variabile, poiché capita spesso che qualcuno di loro si dimetta dopo qualche mese di servizio per aver trovato un lavoro migliore: attualmente, se non ricordo male ma potrei sbagliarmi, dei tre che erano stati scelti per il servizio, ne è rimasta una sola.

Con questo organico così composto si riesce appena a coprire l’orario attuale, per cui un’estensione sostanziale dello stesso è fuori discussione. Inoltre, qualsiasi sperimentazione di revisione dello stesso dovrà attendere l’esaurimento della procedura di mobilità provinciale e la sostituzione di quel dipendente di cui sopra.

Ad ogni modo, la proposta di revisione dell’orario è così strutturata:
- ogni giorno, posticipo dell’apertura mattutina di 30’ (8.30 -> 9.00);
- il mercoledì e il venerdì, orario continuato dalle 9.00 alle 19.00 (quindi, con ulteriore posticipo della chiusura di 30’).

L’idea è di attivare una sperimentazione, con l’orario qui descritto, di sei mesi, al termine della quale sottoporre all’utenza un questionario di gradimento per verificare l’opportunità di mantenerlo definitivamente. Si è invece preferito evitare di sottoporre all’utenza un questionario preventivo, per “aggiornare” i dati di quello di due anni fa alla situazione attuale (da ricordare che nel 2014, quando quel questionario fu attivato, la mediateca era ancora separata e aperta solo il pomeriggio ed era ancora presente l’aula studio): si è ritenuto che un eccessivo coinvolgimento dell’utenza creerebbe un’aspettativa nella stessa che però, stante le già descritte difficoltà, sarebbe difficile soddisfare.

Detto ciò, posto che, come detto, è necessario attendere l’esito della procedura di mobilità e l’inserimento della nuova figura, credo che di questa sperimentazione ne riparleremo non prima di Natale.

**Comment by achitac** [comment]
[Report questionario.pdf](https://github.com/open-comune/desio/files/519113/Report.questionario.pdf)

**Comment by achitac** [comment]
In breve: l'idea c'è (due giorni ad orario continuato e orario serale esteso tutti i giorni fino alle 19) e, perlomeno da parte dell'Assessore Redi, la volontà politica di farlo anche; il problema principale è la carenza (e il turn over) del personale, riguardo al quale è attiva al momento una pratica di sostituzione, di un dipendente che a breve andrà in pensione, tramite mobilità. Compiuta questa pratica, ottenuto quindi un quadro stabile del personale in funzione, si potrà mettere in atto una sperimentazione con l'orario suddetto, al termine della quale decidere se portarla a regime o meno.

**Comment by emilianoferrari1** [comment]
Grazie Achille,
so bene come ti sta a cuore questa cosa...e come la maggioranza dei 36-50 enni anche io ne sono molto entusiasta... ;)
Perché una sperimentazione di tre mesi diventa un riferimento di massima sulla fruibilità di un servizio? 
Visto il questionario e la tipologia di persone che hanno avuto interesse nel dare delle risposte, quali sono state le attività e con quale frequenza sono state svolte?
Stante che se un dipendente pubblico va in pensione o in maternità non possiamo fasciarci la testa...ma se un incaricato dalla cooperativa o un volontario concludono la loro attività per varie ragioni, perchè non sono sostituiti ? Che contratto c'è per le cooperative? Quali vantaggi per i volontari? E' possibile ripensare ad una politica di incentivi per chi svolge un il lavoro negli orari serali o festivi?
Solo per curiosità, ma quale ufficio si occupa del personale della biblioteca ? 
Ciao,
A presto!
Emiliano

**Comment by achitac** [comment]
- Perché una sperimentazione di tre mesi diventa un riferimento di massima sulla fruibilità di un servizio? 

A mio parere, tre mesi sono un periodo sufficiente per capire l'efficacia di una variazione nel consueto orario. Piuttosto, mi concentrerei sulle modalità della sperimentazione.
- Visto il questionario e la tipologia di persone che hanno avuto interesse nel dare delle risposte, quali sono state le attività e con quale frequenza sono state svolte?

Se ti riferisci alle modalità del questionario, questo è stato a) inviato via mail agli utenti del servizio che all'iscrizione avevano comunicato il proprio indirizzo, b) in formato cartaceo disponibile presso il banco prestiti, c) pubblicato sul sito della biblioteca. 
Se ti riferisci alle modalità della sperimentazione, è stato esteso l'orario di chiusura di un giorno alla settimana (il giovedì) fino alle 22.30, contestualmente sopprimendo la mattina dello stesso giorno. Secondo me, lo scarso successo (in alcune sere si registrava una presenza di sole tre persone all'interno della biblioteca) è derivato dal fatto che la sperimentazione è stata proposta in estate, da metà luglio a fine settembre. Resta il fatto che anche fra gli studenti, che perlomeno nel mese di settembre, in concomitanza degli ultimi appelli universitari, potevano essere i maggiori fruitori del servizio, questa estensione di orario non ha trovato ol favore della maggior parte dell'utenza.
- Stante che se un dipendente pubblico va in pensione o in maternità non possiamo fasciarci la testa...ma se un incaricato dalla cooperativa o un volontario concludono la loro attività per varie ragioni, perchè non sono sostituiti ? Che contratto c'è per le cooperative? Quali vantaggi per i volontari? 

In questo momento l'incaricata della cooperativa che è andata in maternità è sostituita dal suo collega della cooperativa, che ha esteso il proprio orario da un part time ad un orario pieno, quindi non c'è nessun ruolo "scoperto", almeno per quanto riguarda quella categoria di bibliotecari. Non so dirti che tipo di contratto abbiano loro con la cooperativa; questa invece ha un contratto credo biennale con l'amministrazione. Per quanto riguarda il servizio civile, il comune può sostituire un operatore dimissionario solo se questi presenta le dimissioni entro un certo termine, se non sbaglio i primi tre mesi del servizio, e lo sostituisce con il primo della graduatoria; altrimenti deve attendere il successivo bando del servizio civile. 
A parte questi casi insomma, la carenza di personale è proprio strutturale, endemica al servizio. Un modo per farvi fronte potrebbe essere implementare il servizio offerto dalla cooperativa allo scadere del contratto, richiedendo un maggior numero di ore (in sostanza, pagando un nuovo operatore senza assumerlo direttamente).
Per quanto riguarda invece la possibilità di trovare dei volontari che assistano il personale di biblioteca (in modo simile a quanto fatto con le Biblioaninatrici, volontarie appunto che partecipano all'organizzazione degli eventi culturali che si tengono in biblioteca, insieme ai bibliotecari stessi e alla cooperativa Stripes, partner di Parco delle Culture), è un percorso su cui mi sembra di aver capito, dall'incontro, ci siano molti dubbi, principalmente perché secondo loro l'impegno che i volontari danno è spesso incostante, per cui non si potrebbe fare affidamento su di essi per eventuali variazioni nell'orario del servizio.
- E' possibile ripensare ad una politica di incentivi per chi svolge un il lavoro negli orari serali o festivi?

Il fatto è che non manca chi vuole fare il lavoro negli orari serali o festivi, ma manca proprio chi lo potrebbe fare in orari 'in più': con l'orario attuale copriamo il totale delle ore di lavoro dei dipendenti, e il comune non può assumerne di nuovi.
- Solo per curiosità, ma quale ufficio si occupa del personale della biblioteca ?

L'Area Persone e Famiglia, diretta dalla d.ssa Elvira Antenucci (http://www.comune.desio.mb.it/servizi/menu/dinamica.aspx?idArea=20007&idCat=30080&ID=30080&TipoElemento=categoria)

**Comment by emilianoferrari1** [comment]
Grazie Achille !!
Mi spiego, penso che tre mesi siano pochi per una sperimentazione, perché non si da modo di conoscere il servizio a persone come me che lo utilizzano in modo saltuario (36-50anni).
Io vado volentieri in biblioteca a leggere dei libri alle mie bimbe e se avessi saputo di potervi accedere fino alle 19/20 sarei andato qualche volta in più. 
È vero che i volontari possono essere incostanti, ma se li coinvolgi in progetti a tempo , forse si potrebbe portare la sperimentazione ad 1 anno.... 
cosa ne pensi ?
Ripetizioni scolastiche , presentazioni libri (anche con web radio), letture programmate , serate cinema a tema, saggi scuole di musica, teatro ecc...

**Comment by olistik** [comment]
comunicazione inoltrata alla biblioteca il 2016-10-07

**Comment by olistik** [comment]
Ho letto con troppa superficialità il contributo di @achitac e quindi potevo evitare di inoltrare la comunicazione alla Biblioteca..

La proposta di revisione dell'orario sarebbe quindi questa:
- lunedì: 9:00-12:15, 14:30-19:15
- martedì: 9:00-12:15, 14:30-19:15
- **mercoledì: 9:00-19:00**
- giovedì: 9:00-12:15, 14:30-19:15
- **venerdì: 9:00-19:00**
- sabato: 9:00-12:15, 14:30-19:15
- lunedì: 9:00-12:15, 14:30-19:15
- domenica: chiuso

e partirebbe solo in seguito alla risoluzione della procedura di mobilità che avverrà verosimilmente dopo Natale 2016.

A questo punto penso si possa "congelare" questa issue e riaprirla a fine anno.

@achitac @emilianoferrari1 sensato?

**Comment by achitac** [comment]
Per me sensato. Ovviamente, se dovessi avere news sulla mobilità o comunque sull'argomento, ve le farei comunque avere qui.

**Comment by olistik** [comment]
Pare che la Biblioteca abbia proseguito nell'iter:

[Post Facebook dell'ass. Redi](https://www.facebook.com/cristina.redi.1/posts/1841417442775009)

@achitac sentiti libero di espandere qui eventuali peculiarità del percorso :-)

Penso che sia un'ottima cosa tenere traccia delle buone sperimentazioni :-)

**Comment by olistik** [comment]
Orario sperimentale **dal 20 Marzo al 27 Giugno 2017**:

| Giorni | Mattino | Pomeriggio|
|-------|--------|-------------|
| lunedì | _ | 14:30 - 18:30 |
| martedì | 09:00 - 12:30 | 14:30 - 18:30 |
| mercoledì (**continuato**) | 09:00 | 19:00 |
| giovedì | 09:00 - 12:30 | 14:30 - 18:30 |
| venerdì (**continuato**) | 09:00 | 19:00 |
| sabato | 09:00 - 12:30 | 14:30 - 18:30 |
| domenica | _ | _ |

La **sezione ragazzi (2° piano)** chiude alle 18:30 e resta chiusa le mattine di lunedì, mercoledì e venerdì.

## BIBLIOTECA E MEDIATECA CIVICA DI #DESIO: SEMPRE DI PIU’ UN LUOGO PER STARE

Con l’orario sperimentale in vigore dal prossimo 20 marzo, aumenta di complessive 5,15 ore l’apertura al pubblico della [Biblioteca Civica di Desio](https://www.facebook.com/BibliotecaDesio/), due giornate – mercoledì e venerdì – divengono ad orario di apertura continuato e con chiusura alle 19, posticipata inoltre di 15 minuti la chiusura del lunedì, martedì e sabato.
“L’ impostazione di questo orario sperimentale è frutto di un ascolto attivo della nostra utenza – racconta l’Assessore alla Cultura e [Biblioteca Civica di Desio](https://www.facebook.com/BibliotecaDesio/), [Cristina Redi](https://www.facebook.com/cristina.redi.1) – con un questionario, avevamo chiesto ai nostri utenti il loro giudizio sugli orari della Biblioteca, ricevendo come risposta un giudizio complessivamente buono. Nelle risposte abbiamo trovato indicazioni di possibili ulteriori miglioramenti attraverso l’introduzione dell’orario di apertura continuato e del posticipo della chiusura serale. E’ quindi in queste due direzioni che ci siamo mossi, mettendo a punto l’orario sperimentale che partirà il prossimo 20 marzo per terminare il 27 giugno; in questo periodo monitoreremo presenze, prestiti, e gradimento dell’utenza per arrivare così, dopo l’estate, alla messa a punto di un orario definitivo.” 

Conclude Redi: “L’ascolto e il dialogo con l’utenza quindi proseguiranno, così come proseguirà l’esperienza dei gruppi di lettura e l’offerta di appuntamenti di culturali per le diverse fasce d’età dei lettori che stanno facendo divenire sempre di più la Biblioteca della nostra Città un luogo, oltre che di lettura, di animazione culturale e aggregazione sociale.“

Il nuovo orario, sperimentale fino al 27 giugno 2017, fa della struttura desiana la biblioteca con il maggior numero di ore di apertura al pubblico tra le quelle del sistema @BrianzaBiblioteche con numero di abitanti confrontabili. 

## ORE TOTALI DI APERTURA - COMPARAZIONE 

| Comune | Ore |
|---------|-----|
|Desio| 46.30|
|Cesano Maderno| 36.50|
|Lissone| 36.30|
|Meda| 36.00|
|Seregno| 35.00|
|Limbiate| 27.3|
