### ISSUE TITLE
Visione CITIZENFOUR e workshop sulla privacy online

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#12]
![11754783_883171905107789_3882627917624838018_o](https://cloud.githubusercontent.com/assets/21038/19146016/e2f5797e-8bb1-11e6-875f-85a92b2621a9.jpg)
## Descrizione

Giornata divulgativa sul tema del [Whistleblowing](https://it.wikipedia.org/wiki/Whistleblower) e della tutela della privacy e sto esplorando un eventuale interesse da parte delle scuole desiane ad una visione gratuita del documentario CITIZENFOUR di Laura Poitras.

La reputo una preziosa opportunità per aiutare gli studenti a formare una sensibilità riguardo al tema della privacy (online e offline).

[Scheda del documentario](http://catndocs.com/index.php/categories/politics/663-citizenfour)

Nel caso risultasse un interesse potremmo anche organizzare un workshop gratuito hands-on in cui far sperimentare agli studenti gli strumenti e i processi digitali a tutela della privacy:
- cifratura simmetrica/asimmetrica con [GPG](https://it.wikipedia.org/wiki/GNU_Privacy_Guard)
- la privacy nelle e-mail
- la privacy nelle piattaforme social
- il whistleblowing (attori e servizi)

Il documentario tratta il percorso che ha portato [Edward Snowden](https://it.wikipedia.org/wiki/Edward_Snowden) a diffondere documenti che dimostrano una massiva e indiscriminata violazione della privacy.

Il film dura 114 minuti e verrebbe trasmesso in inglese con i sottotitoli in italiano.
## Collaborazioni
- [ ] richiesta di patrocinio al Comune
- [ ] permessi da parte di [PraxisFilms](http://www.praxisfilms.org/contact/)
- [x] interesse/disponibilità Majorana
- [ ] interesse/disponibilità Fermi
- [ ] interesse/disponibilità Globaleaks
- [ ] interesse/disponibilità Hubout Makers Lab
## Materiale

> What are your best arguments against total surveillance?
> 
> Person A: "I don't want total surveillance, I want my privacy back while using the internet."
> Person B: "What's your problem? If you don't break the law you have nothing to hide."

[Answer](https://www.quora.com/What-are-your-best-arguments-against-total-surveillance/answer/Judith-Meyer)

> The right to privacy is a human right. It can only be suspended when there's a concrete suspicion that this concrete person has committed a crime / is about to commit a crime. This means that the US police or intelligence services should only be allowed to access and store e-mail and other private information on a person-by-person basis - certainly no mass storage and no pre-emptive storage.
> 
> Here is a great video explaining why mass surveillance is a bad idea: [link](https://www.youtube.com/watch?v=iHlzsURb0WI) (there are English subtitles).
> 
> Some arguments from this video:
> 1. When it is known that everything is under surveillance, terrorists will know to use strong encryption or offline communication, so that the only people having their privacy invaded are innocents. Actually this makes it less likely to catch terrorists - if there was no mass surveillance, they might feel safe enough to use the internet for communication.
> 2. If you have nothing to hide, why do you feel uneasy about your parents' or your boss's requests to add you on Facebook? Why do you wear clothes?
> 3. The entire premise of "if you have nothing to hide, you have nothing to fear" is wrong: why is it assumed that citizens' secrets are never legitimate while the state's secrets are always legitimate? Things to fear even while presumed innocent: being held in custody for several weeks (or several years in Guantanamo), having one's computer or work equipment taken away to be searched and retained for months, having one's bank account frozen, even if proven innocent later there is no compensation for such incurred losses.
> 4. Another thing wrong with that premise: why is it assumed that breaking the law is necessarily bad? It could be that the law is unreasonable, as happened in the GDR and any totalitarian regime. We're essentially assuming that the state is always right.
> 5. Knowing that the state is listening in, even if he's not paying attention to you in particular, you will start to censor yourself, not saying things that could be considered controversial, even if you assume that it would be legal to say those things. The ripples are several times greater than the direct repercussions of censorship.
> 6. There are already known instances of this internet surveillance being misused, of people being arrested because they posted comments on Twitter or Facebook that anyone would have understood to be sarcastic rather than actual threats. For example, a group of Texan teenagers were playing League of Legends online and one of them told the other "You're fucked up in the head" and the other replied "Oh yeah, I'm fucked up in the head, I'm going to shoot up a school full of kids and eat their still beating hearts. LOL. J/K."  This teenager has now spent 6 months in prison and is expecting a sentence of 10 years because of making a "terrorist threat". If that's how US authorities react, can you even afford to be sarcastic? Can you afford to joke? You start to censor yourself when talking to your friends online.  (the video has more examples from 4:45)
> 7. Surveillance cost a lot of money. With hundreds of billions of hours of surveillance every day, we have so far only managed to uncover a handful of terrorist ploys, none of them sophisticated enough to work; in one case they were initiated by an intelligence agent even as the terrorist group was too clueless. It is unthinkable that there aren't any ways that are cheaper, more respectful of human rights and that are way more effective than what we have today. 
> 8. Collections of data can later be abused. For example, sodomy was forbidden in early 1900 Germany and the state kept lists of suspected homosexuals in order to be able to fine them for sodomy. Even if we assume that the lists were legitimate as a way to persecute what was a minor crime, the story goes on: in 1933, the Nazis were able to arrest, castrate or kill tens of thousands of homosexuals because of those lists. Given today's near-complete surveillance with biometric passports, cellphone tracing and everything, Jews would stand no chance in hell nowadays to escape whichever country wanted to harm them. And eventually there will be one that wants to harm them, or another minority.
- https://www.justsecurity.org/33479/a-amendment-digital-age-peter-zenger-lecture/#more-33479
- https://www.washingtonpost.com/news/the-switch/wp/2016/10/11/facebook-twitter-and-instagram-sent-feeds-that-helped-police-track-minorities-in-ferguson-and-baltimore-aclu-says/?postshare=2471476200358604&tid=ss_tw

**Comment by olistik** [comment]
PEC a protocollo.comune.desio@legalmail.it

> Buongiorno,
> 
> vorrei chiedervi la possibilità di ricevere il patrocinio da parte del Comune per il seguente progetto:
> 
> https://github.com/open-comune/desio/issues/12
> 
> Il risultato sarebbe una giornata (o mezza giornata) divulgativa sul tema del Whistleblowing e della tutela della privacy.
> Sto esplorando un eventuale interesse da parte delle scuole desiane ad una visione gratuita del documentario CITIZENFOUR di Laura Poitras.
> 
> La reputo una preziosa opportunità per aiutare gli studenti a formare una sensibilità riguardo al tema della privacy (online e offline).
> 
> Scheda del documentario:
> http://catndocs.com/index.php/categories/politics/663-citizenfour
> 
> Nel caso risultasse un interesse potremmo anche organizzare un workshop gratuito hands-on in cui far sperimentare agli studenti gli strumenti e i processi digitali a tutela della privacy:
> - cifratura simmetrica/asimmetrica con GPG
> - la privacy nelle e-mail
> - la privacy nelle piattaforme social
> - il whistleblowing (attori e servizi)
> 
> Il documentario tratta il percorso che ha portato Edward Snowden a diffondere documenti che dimostrano una massiva e indiscriminata violazione della privacy.
> 
> Il film dura 114 minuti e verrebbe trasmesso in inglese con i sottotitoli in italiano.
> 
> Resto a vostra disposizione per qualunque chiarimento.
> 
> Saluti

**Comment by olistik** [comment]
data: 2016-10-05

Richiesta del permesso di trasmettere il film spedita a studio@praxisfilms.org

**Comment by olistik** [comment]
Risposta di Matteo Bonanno di Hubout Makers Lab:

> Parlando con l'equipe, abbiamo constatato che c'è una discussione in corso da parte nostra con tutte le scuole sui progetti extracurriculari (in cui rientrerebbe anche il tuo). Affiancare alle attività già in previsione anche la tua proposta è interessante, ma per quanto ci riguarda ha ancora bisogno di un po' di tempo proprio per la fase di definizione che stiamo affrontando. Se per te non è un problema attendere un attimo, poi possiamo vedere di fare qualcosa di congiunto.

Ho richiesto a Davide Scorza un'idea della tempistica prevista.

**Comment by Raxco** [comment]
Partecipazione Whistleblowing Solutions: 
-contesti teorici di riferimento per il Whistleblowing
- soluzione tecnologica open source, GlobaLeaks

**Comment by emilianoferrari1** [comment]
Ciao Maurizio,
sarebbe interessante sapere se può interessare ai professori delle scuole. Rimango disponibile se serve una mano ;-).
i sapere!
Ciao,
Emiliano

**Comment by olistik** [comment]
@emilianoferrari1 ho avuto modo di contattare [Flavia Schiatti](https://www.facebook.com/flavia.schiatti) su indicazione di [Davide Taccagni](https://www.facebook.com/davide.taccagni) uno degli admin del gruppo [Studenti Majorana Desio](https://www.facebook.com/groups/Rappresentanti.Majorana/), la quale mi ha detto che avrebbe passato questa proposta alla referente sul tema.

Penso che chiedere un parere ed eventualmente un interessamento anche ad altre scuole sia un'ottima idea :-)

Hai qualche riferimento a disposizione per contattarlo?

**Comment by emilianoferrari1** [comment]
Yes!! in privato ;-)

**Comment by olistik** [comment]
Richiesta spedita a info@catndocs.com

**Comment by olistik** [comment]
La prof.ssa Schiatti mi ha detto che hanno una programmazione già molto fitta ma mi ha comunque passato il riferimento della prof.ssa Monguzzi.
Proverò a contattarla domani.

**Comment by olistik** [comment]
Comunicazione spedita alla prof.ssa Monguzzi

**Comment by olistik** [comment]
migrato su https://github.com/open-comune/progetta-desio/issues/19
