### ISSUE TITLE
Affissione di manifesti: richiesta di esenzione d'imposta per associazioni e gruppi informali

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#14]
## Responsabili
- Emiliano Ferrari
## Premessa

Riguardo le affissioni pubblicitarie esiste un regolamento non molto chiaro, perché doppio.

Uno è il regolamento Edilizio in cui si regolano gli _"artefatti"_, l'altro è un riferimento all'[Art. 1](https://hyp.is/pEJ5fIxZEeasoc8ieqHdEQ/www.comune.jesi.an.it/MV/leggi/dlvo507-93.htm), [D.Lgs. n. 507/93](http://www.comune.jesi.an.it/MV/leggi/dlvo507-93.htm) relativo alle pubblicità anche di vetrofanie pubblicitarie.

Nel caso più comune di una associazione o un gruppo informale di cittadini, il "problema" secondo me, è per l'affissione di manifesti e locandine in luoghi pubblici.

L' Art. 1, D.Lgs. n. 507/93, al punto , [Art.17 Esenzioni dell'imposta](https://hyp.is/klaA3IxZEea97DsIKK8hYQ/www.comune.jesi.an.it/MV/leggi/dlvo507-93.htm), dice che si è esenti dall'imposta quando la pubblicità si riferisce all'attività negli stessi esercitata.

Per come la capisco io, significa per esempio che se il CdQ, attacca manifesti sulla porta della Baita, non deve pagare niente, al contrario, se attacca manifesti sulle bacheche o negozi dei commercianti, dovrà pagare la ICOPU e questo vale per tutti, associazioni, partiti, gruppi di cittadini...
## Richiesta

Dato che sempre l' Art. 1, D.Lgs. n. 507/93, prevede nell' Articolo 3 "Regolamento e tariffe", che:

> "[il Comune è tenuto ad adottare apposito Regolamento](https://hyp.is/-vkTOoxYEeaHo2fMAHT9ng/www.comune.jesi.an.it/MV/leggi/dlvo507-93.htm) [..] [e può stabilire limitazioni e divieti per particolari forme pubblicitarie in relazione ad esigenze di pubblico interesse"](https://hyp.is/_ie-OoxYEeaE9p8BG_qSkA/www.comune.jesi.an.it/MV/leggi/dlvo507-93.htm) [..]

E' possibile aggiungere a questo regolamento per l'applicazione dell'imposta sulla pubblicità, che le associazioni ed i gruppi informali di cittadini (art.18 della costituzione), possono essere esenti dall'imposta per l'affissione dei manifesti riguardanti le loro attività senza scopo di lucro?
## Attività
- [x] spedire la comunicazione al Comune

**Comment by olistik** [comment]
@emilianoferrari1 se pensi che la proposta così com'è sia completa, possiamo spedirla a partecipazione@comune.desio.mb.it, fammi sapere :-)

**Comment by emilianoferrari1** [comment]
Ho già avanzato la proposta agli assessori, Redi, Borgonovo e Gerosa, attendo un loro accenno alla cosa...
Nel frattempo parlando con TRE ESSE ITALIA, concessionaria per la ICOPU , ho capito che se un manifesto affisso alla vetrina, pubblicizza un' attività relativa alla stessa attività del del luogo di affissione, sotto i 0,5mq non ha l'obbligo d'imposta. E' comunque necessario mostrare nel manifesto il periodo dell'attività e non deve pubblicizzare terzi.

Quindi la proposta diventa più chiara, perchè si richiede semplicemente di annullare il pagamento dell'imposta per le locandine con le stesse caratteristiche di cui sopra, ma anche per i luoghi (vetrine) non relativi l'iniziativa e solo per le iniziative sociali senza scopo di lucro con fini di aggregazione ed informazione.
Rimango in attesa ...... 👍

**Comment by emilianoferrari1** [comment]
Neanche un diniego, non una risposta. @olistik , direi che se hai la possibilità di inviare una PEC ti ringrazio... 
    Si credo che la proposta come sopra, sia completa, non voglio inserire inutili discussioni come il fatto che già oggi, "alcuni" manifesti sulle vetrine non hanno il timbro del versato pagamento della tassa, per cui cambierebbe la legge ma non la tradizione ....  ;-)

**Comment by olistik** [comment]
@emilianoferrari1 ho spedito la comunicazione a partecipazione@comune.desio.mb.it mettendoti in CC

**Comment by olistik** [comment]
richiesta di aggiornamento spedito all'ufficio Partecipazione, mettendo in copia l'assessore Moro.

**Comment by emilianoferrari1** [comment]
Maurizio, si potrebbe creare una wiki anche per la semplificazione dei regolamenti comunali?
Mi spiego:
1) se venisse presa in carico la richiesta di **modifica dell'imposta ICOPU per le attività senza scopo di lucro**, potrebbe aprirsi il terreno anche verso altre regole, come per esempio lo snellimento di certe forme di autorizzazione, in seguito a semplici manifestazioni di interesse.

L'articolo 14 del Regolamento di polizia urbana dice: "Nei luoghi pubblici è vietato collocare addobbi, luminarie o simili, senza avere ottenuto conforme permesso dall’Autorità Comunale"
Se ci fosse un sistema informatico che permette ad ogni cittadino di verificare in autonomia questo tipo di attività in un posto ed in un tempo specifico, non ci sarebbe bisogno di attendere il consenso dell'Autorità Comunale e di far lavorare inutilmente personale ...

2) O forse è meglio aprire una nuova ISSUE per chiedere il **permesso di mettere 4 palline di Natale su un albero** ogni volta? :-(

**Comment by olistik** [comment]
migrata su https://github.com/open-comune/progetta-desio/issues/20
