### ISSUE TITLE
CoderDojo Desio

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#15]
## Cos’è CoderDojo

[fonte](http://www.coderdojoitalia.org/cose-coderdojo/)

> I CoderDojo sono club gratuiti il cui obiettivo è l’insegnamento della programmazione informatica ai più piccoli. CoderDojo è un movimento aperto, libero e totalmente gratuito organizzato in centinaia di club indipendenti sparsi in tutto il mondo. Ogni Dojo organizza le proprie attività senza scopo di lucro, rispettando le indicazioni della Charter internazionale stilata dalla Fondazione Internazionale CoderDojo. Le attività di formazione dei nostri club ruotano intorno al gioco, lo scambio reciproco ed il peer learning, secondo l’unica regola fondamentale di ogni dojo: Be Cool.
> 
> In Italia sono attivi dal 2012 oltre 40 dojo diffusi su tutto il territorio nazionale (la lista completa dei dojo è disponibile su www.coderdojoitalia.org) ed ogni giorno nuovi gruppi di volontari si approcciano al movimento per aprire una nuova sede in cui ospitare incontri periodici per i bambini del proprio territorio. Migliaia di bambini hanno già partecipato agli incontri italiani del movimento, imparando ad utilizzare linguaggi di programmazione come HTML, Javascript e CSS, creare piccoli videogiochi con Scratch e programmare hardware con Arduino.
> 
> Per informazioni è possibile contattare il movimento nazionale coderdojo all’indirizzo www.coderdojoitalia.org o scrivendo a coderdojoitalia@gmail.com
- [CoderDojo Milano](http://coderdojomilano.it/)
- Mappa dei CoderDojo italiani: [link](http://www.coderdojoitalia.org/)
- [Sito internazionale](https://coderdojo.com/)
## Attività
- [ ] Trovare una persona di riferimento (il _Champion_)
- [ ] valutare collaborazione con [Hubout Makers Lab Desio](https://www.facebook.com/huboutmakerslab.desio)
- [ ] seguire i passaggi presenti [qui](http://www.coderdojoitalia.org/far-partire-un-dojo/)

**Comment by Saram0n** [comment]
Due informazioni: 
CoderDojo Lissone dovrebbe avere già preso contatti con Hubout, meglio sentire questi ultimi per non sovrapporsi. Il nostro riferimento più vicino credo potrebbe essere anche CoderDojo Brianza.
Oltre a persone che conoscono i programmi in uso nei CoderDojo (es.: Scratch) servono volontari anche non esperti per dare supporto durante le sessioni (caldamente invitati quindi i genitori dei giovani sviluppatori).

**Comment by olistik** [comment]
Aggiungo un intervento di @ipersoft:

> Fare da Champion mi sembra un po' impegnativo senza una esperienza sul campo. Se riusciamo ad affiancarci ad un gruppo già costituito preferirei.

Penso che si possa chiedere ai vicini di Lissone di aiutarci con il primo evento, ma se vogliamo dare una periodicità all'iniziativa serve comunque un _Champion_ desiano (modo pomposo per dire _referente_).

**Comment by olistik** [comment]
migrata su https://github.com/open-comune/progetta-desio/issues/21
