### ISSUE TITLE
Adeguamento accessibilità scalinate ufficio ASL

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#18]
Ufficio di via Ugo Foscolo 26:

[![Ufficio di Via Ugo Foscolo 26](https://cloud.githubusercontent.com/assets/21038/19302601/0cba8256-9065-11e6-93e2-b8d3d0951e38.png)](https://www.google.it/maps/@45.6134637,9.2039915,3a,37.5y,31.35h,86.23t/data=!3m6!1e1!3m4!1ss7-o_yvgdYoFsTM4I5R3FQ!2e0!7i13312!8i6656?hl=en)

[mappa](https://www.google.it/maps/@45.6134637,9.2039915,3a,37.5y,31.35h,86.23t/data=!3m6!1e1!3m4!1ss7-o_yvgdYoFsTM4I5R3FQ!2e0!7i13312!8i6656?hl=en)

> ho scritto al comune per quelle favolose scalinate della ASL. 
> Di seguito la risposta:
> "Gent.ma,
> abbiamo verificato con il nostro Ufficio Tecnico che quanto da lei segnalato non è un intervento a carico del Comune bensì dell'Asl."

[fonte](https://www.facebook.com/groups/823777737638221/permalink/1555519304464057/)

Pagina dei contatti dell'ASL: [link](http://www.aslmonzabrianza.it/ita/Default.aspx?SEZ=4&PAG=58)

Sarebbe utile raccogliere l'interesse dei cittadini in un'unica comunicazione. Una sorta di raccolta firme.
Possiamo spedire una PEC a protocollo@pec.ats-brianza.it mettendo in allegato i nominativi delle persone che sono disposte a "metterci la faccia".

A questo scopo possiamo aprire un petizione su http://www.activism.com/ o su https://change.org o anche più semplicemente fare in modo che chiunque voglia partecipare mi spedisca un'e-mail con il proprio nome, cognome e scrivendomi una liberatoria in cui asserisce di non aver fornito informazioni false e che mi permette di usare queste informazioni per i fini della petizione.

Qualche avvocato come potrebbe aiutarci nella stesura della liberatoria.
## Sistemi di petizioni
- raccolta adesioni via e-mail
- www.activism.com
- change.org
## Attività
- [x] scelta del sistema di petizione
- [ ] scrittura liberatoria
- [ ] raccolta adesioni
- [ ] spedizione comunicazione
## Adesioni preliminari

[Sondaggio Facebook](https://www.facebook.com/groups/823777737638221/permalink/1555598367789484)
- Alessandra Tagliabue: [Facebook](https://www.facebook.com/alessandra.tagliabue.54)
- Alessia Vecchio: [Facebook](https://www.facebook.com/profile.php?id=1459758507)
- Andrea Villa: [Facebook](https://www.facebook.com/andrea.villa.505)
- Antonella Carcione: [Facebook](https://www.facebook.com/antonella.carcione)
- Antonio Leanza: [Facebook](https://www.facebook.com/leon.anton.zaia)
- Claudia Pluda: [Facebook](https://www.facebook.com/claudia.pluda)
- Clemente Colombo: [Facebook](https://www.facebook.com/clemente.colombo)
- Damiano Donadoni: [Facebook](https://www.facebook.com/damiano.donadoni)
- Denis Franzini: [Facebook](https://www.facebook.com/denis.franzini)
- Francesca Colombo: [Facebook](https://www.facebook.com/francesca.colombo88)
- Iris Luraschi: [Facebook](https://www.facebook.com/profile.php?id=100010817282863)
- Ivana Damiani: [Facebook](https://www.facebook.com/ivana.damiani.5)
- La Deni: [Facebook](https://www.facebook.com/profile.php?id=100009379842574)
- Mariarosa Mazzocchi: [Facebook](https://www.facebook.com/mariarosa.mazzocchi)
- Marilena Raimondo: [Facebook](https://www.facebook.com/marilena.raimondo.5)
- Maurizio De Magnis: [Facebook](https://www.facebook.com/maurizio.demagnis)
- Miriam Demma: [Facebook](https://www.facebook.com/miriam.demma)
- Nelsi Callivà: [Facebook](https://www.facebook.com/nelsi.calliva)
- Nicola Orietta: [Facebook](https://www.facebook.com/barberionicola)
- Ornella Guzzo: [Facebook](https://www.facebook.com/ornella.guzzo.9)
- Prisca Van Deursen: [Facebook](https://www.facebook.com/prisca.vandeursen)
- Rosa Catizzone: [Facebook](https://www.facebook.com/rosa.catizzone)
- Rosaria Gelosa: [Facebook](https://www.facebook.com/rosaria.gelosa)
- Simona Albino: [Facebook](https://www.facebook.com/simona.albino)
- Simona Pantaleo: [Facebook](https://www.facebook.com/simona.pantaleo.73)
- Tiziana Monguzzi: [Facebook](https://www.facebook.com/tizianamonguzzi)
- Valentina Ravasio: [Facebook](https://www.facebook.com/valentina.ravasio.75)

**Comment by emilianoferrari1** [comment]
Ciao Maurizio, c'era in progetto di spostare gli uffici dell'Asl , per cui non so quanto sia interessato il comune alla loro sistemazione ....
http://quibrianza.it/cronaca/desio/corti-spostare-l-asl-c-e-il-problema-della-destinazione-d-uso-dell-ex-tribunale.html

**Comment by olistik** [comment]
@emilianoferrari1 grazie Emiliano, la notizia è stata ritrovata anche da Mariarosa Mazzocchi ([link](https://www.facebook.com/groups/823777737638221/permalink/1555699587779362/)) di una ricondivisione di Giorgio Gerosa ([link](https://www.facebook.com/groups/823777737638221/permalink/1241671195848871/)) di un post del Comune di Desio ([link](https://www.facebook.com/Comune.di.Desio/photos/a.128827830535049.33972.103441483073684/947420878675736/?type=3))

> alla Fiera dell'est, per due soldi..

## 

> #Desio Spostamento della sede dell'ASL presso i locali dell'ex Tribunale: il punto della situazione e un po' di chiarezza
> 
> I provvedimenti governativi del settembre 2011 hanno cancellato le sedi distaccate dei tribunali e dei giudici di pace, generando per Desio ed in generale per tutti i comuni coinvolti, il problema del riutilizzo delle sedi lasciate libere.
> 
> Il Tribunale è stato individuato come nuova sede degli uffici ASL di Desio ed a tal proposito, nell’ottobre 2013 è stato sottoscritto tra il Comune di Desio e l’ASL di Monza Brianza un protocollo d’intesa volto a verificare la fattibilità dello spostamento (in seguito confermata) ma comunque subordinato al rilascio dell’immobile con piena libertà di utilizzo per il comune di Desio da parte del Ministero della Giustizia.
> 
> Da quel momento l'Amministrazione Comunale ha avviato le interlocuzioni con il ministero ed il tribunale di Monza per capire da quando il comune avrebbe potuto disporre dell’immobile, stante la decisione irreversibile di chiusura della sede distaccata.
> 
> La situazione si è definitivamente chiarita nel gennaio 2015 quando il direttore generale del ministero della giustizia ci comunicava che sull’immobile, pur essendo di proprietà comunale, esisteva un vincolo di destinazione in quanto realizzato con fondi della cassa Depositi e Prestiti. In pratica il Comune poteva disporne ma, in qualsiasi momento, il ministero avrebbe potuto richiederlo indietro con l’obbligo di riconsegna in quanto vincolato all’utilizzo giudiziario. A questo punto la situazione con ASL si è arenata in quanto essendo previsti notevoli investimenti per il suo riutilizzo ASL, giustamente, richiedeva la disponibilità dell’immobile incondizionata.
> 
> "Della vicenda - racconta il Sindaco roberto Corti - ho interessato la senatrice Lucrezia Ricchiuti che ha seguito direttamente a Roma la questione, scoprendo che il problema non riguardava solamente Desio, ma praticamente la quasi totalità dei i comuni interessati dalla soppressione delle sedi distaccate."
> 
> La Senatrice Ricchiuti si è attivata con il Ministero di Giustizia a Palazzo Chigi per individuare una possibile soluzione.
> 
> Questa la sua comunicazione mail al Sindaco Corti dello scorso 12 ottobre: “Il 25 di settembre mi sono recata dal capo ufficio legislativo del ministero della giustizia, dott. Santalucia per illustrargli il problema del Tribunale di Desio, nello specifico il vincolo che grava su tutti gli immobili destinati alla giustizia e che in base all'art. 19 della legge 119 del 1981 possono essere, se liberi, utilizzati per altri scopi, mantenendo però la destinazione a uso giustizia. Ciò significa che questi immobili potrebbero in qualsiasi momento essere richiesti dal Ministero della Giustizia per i suoi scopi.
> Ho pertanto proposto di modificare questa norma e di fare un emendamento da presentare nella legge di stabilità.
> Venerdì scorso ho avuto la conferma da parte del Ministero della fattibilità della mia proposta che è stata elaborata dall'ufficio legislativo e ora è al vaglio del ministro Orlando.
> Martedì 20 ottobre incontrerò il capo di gabinetto del ministro Orlando per discutere ulteriormente la questione.”
> 
> "Sembrano esserci dei possibili spiragli positivi sulla vicenda - conclude il Sindaco - e confidiamo che con la nuova legge di stabilità la questione venga definitivamente risolta".

**Comment by olistik** [comment]
A questo punto le considerazioni sono 2:
1. il 19 Ottobre 2015, quindi praticamente 1 anno fa, la soluzione "sembrava vicina"
2. la risposta fornita ad Antonella Carcione ([link](https://www.facebook.com/groups/823777737638221/permalink/1555519304464057/)) non mi sembra soddisfare le necessità sottintese

> Gent.ma,
> abbiamo verificato con il nostro Ufficio Tecnico che quanto da lei segnalato non è un intervento a carico del Comune bensì dell'Asl.

**Comment by emilianoferrari1** [comment]
E comunque che risposta è ?
Lo stabile non è comunale? 🤔

**Comment by olistik** [comment]
Riporto la considerazione fatta nella discussione Facebook [link](https://www.facebook.com/groups/823777737638221/permalink/1555519304464057/?comment_id=1555783517770969&comment_tracking=%7B%22tn%22%3A%22R%22%7D)

> Alla luce della precedente notizia, il 19 Ottobre 2015, quindi praticamente 1 anno fa, la soluzione "sembrava vicina".
> 
> Noto che il protocollo d'intesa sottoscritto nell'ottobre 2013 tra il Comune di Desio e l'ASL di Monza e Brianza riguarda solamente _una_ opzione possibile, ovvero una strada che è stata esplorata ma che è ora considerabile, in assenza di aggiornamenti, un vicolo cieco.
> 
> Mi sembra quindi che tra le strategie possibili, continuare ad aspettare che una soluzione, teoricamente buona, si sblocchi, a fronte delle problematiche emerse, sia poco proficuo.
> 
> Restano quindi altre opzioni valutabili?
> 
> a) sbloccare la situazione? Come?
> b) Altri immobili che potrebbero essere identificati come destinazione dell'ASL?
> c) soluzioni, anche _costose_, che possano tamponare i significativi problemi di accessibilità che affliggono l'utenza di quei servizi?
> 
> La risposta a queste domande penso che potrebbe arrivare dal Comune, diversamente da quanto asserito nella risposta ad [Antonella Carcione](https://www.facebook.com/groups/823777737638221/permalink/1555519304464057/).
> 
> Se anche dovesse sembrare, non ho alcuna intenzione bellicosa nei confronti del Comune, trovo solo che questa sia una buona occasione per aiutare a sbloccare uno stallo che, comprendendo differenti attori e ostacoli non banali, si sta protraendo da troppo tempo.
> 
> Il contenuto di questa riflessione potrebbe diventare una richiesta nei confronti del Comune, magari supportata dall'interesse documentato in questo contesto da parte delle persone che hanno partecipato alla discussione, che ovviamente rappresentano solo una parte di quelle che subiscono i periodicamente i problemi di accessibilità della struttura menzionata.
> 
> Menziono qui lo stesso [Giorgio Gerosa](https://www.facebook.com/giorgio.gerosa2) sperando che non risulti necessario organizzare una petizione firme per far tornare l'attenzione su questo problema.

**Comment by olistik** [comment]
risposta tramite [commento Facebook](https://www.facebook.com/groups/823777737638221/permalink/1555519304464057/?comment_id=1556164681066186&comment_tracking=%7B%22tn%22%3A%22R0%22%7D) di Giorgio Gerosa:

> Ciao Maurizio, ti suggerisco di fissare un incontro con l' Assessore Buonvicino se ti è possibile, lei è sempre disponibile. Un saluto.

**Comment by olistik** [comment]
http://comune.desio.mb.it/servizi/menu/dinamica.aspx?idArea=8882&idCat=16559&ID=16559&TipoElemento=categoria

Assessore Paola Buonvicino (nata a Calliano AT – 8 giugno 1954)
con Delega a: SERVIZI ALLA PERSONA E ALLA FAMIGLIA

POLITICHE SOCIALI
PIANO DI ZONA
PARI OPPORTUNITA'
SERVIZIO LEGALE
- CURRICULUM VITAE
- Atto di nomina del 6 luglio 2016 
- Compensi connessi all'assunzione della carica
- Importi di viaggi di servizio e missioni pagati con fondi pubblici 

E-mail: assessorebuonvicino@comune.desio.mb.it
Riceve il martedì pomeriggio dalle 15.30 alle 17.30, su appuntamento, telefonando allo 0362 392.341

**Comment by olistik** [comment]
e-mail spedita a assessorebuonvicino@comune.desio.mb.it:

> Buongiorno Paola,
> 
> mi chiamo Maurizio De Magnis e sulla base di un interesse sviluppato da parte di svariati cittadini all'interno di una discussione sul gruppo Facebook "Sei di Desio se" ho approfondito lo stato di accessibilità dell'ufficio ASL sito in via Ugo Foscolo 26:
> 
> [link](https://www.google.it/maps/@45.6134637,9.2039915,3a,37.5y,31.35h,86.23t/data=!3m6!1e1!3m4!1ss7-o_yvgdYoFsTM4I5R3FQ!2e0!7i13312!8i6656?hl=en)
> 
> Qua può trovare i dettagli della discussione:
> 
> https://github.com/open-comune/desio/issues/18
> 
> Le chiedo quindi la disponibilità per fissare un appuntamento e capire quali sono le possibilità e le volontà del Comune a riguardo.
> 
> La ringrazio in anticipo per il tempo dedicatomi/ci e le auguro una buona giornata,
> Maurizio

**Comment by olistik** [comment]
Appuntamento fissato con l'assessore Buonvicino, martedì 25 alle 17.

**Comment by olistik** [comment]
Resoconto prodotto sulla Wiki: [link](https://github.com/open-comune/desio/wiki/OAA:-Osservatorio-Accessibilit%C3%A0-ASL).
Chiudo questa issue.

**Comment by olistik** [comment]
Anzi, essendo comunque un'attività in corso, la lascio aperta e la sposto nello stato "In Svolgimento" nel progetto.

**Comment by olistik** [comment]
migrata su https://github.com/open-comune/progetta-desio/issues/23
