### ISSUE TITLE
Proposta restrizione della presenza delle slot machine

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#19]
Seguendo l'esempio di Anacapri:

> La via italiana per la liberazione dalle macchinette mangiasoldi passa da Anacapri, primo comune italiano senza slot machine. A vincere la battaglia contro l’azzardo è stato il sindaco Francesco Cerrotta.  
> 
> Come avete fatto?  
> «Abbiamo redatto un regolamento che proibisce l’installazione di apparecchi a distanza di 150 metri da luoghi sensibili. Nell’elenco ci sono scuole, associazioni, bancomat, centri sportivi e stabilimenti balneari».  
> 
> Quindi non è un divieto assoluto?  
> Di fatto sì, perché nel Comune non esistono zone idonee all’installazione di slot. Chi aveva le macchinette, dal primo gennaio le ha dovute togliere.  
> 
> Perché avete deciso di sottoporre il regolamento a un referendum popolare?  
> Perché era giusto coinvolgere la popolazione. Abbiamo chiesto ai cittadini se erano d’accordo con la nostra azione e oltre nove su dieci si sono detti favorevoli al divieto. Il risultato ci ha dato una mano anche nelle aule dei tribunali 
> 
> Ci sono stati ricorsi?  
> Sì. Ma abbiamo vinto sia davanti al Tar che al Consiglio di Stato. I giudici hanno stabilito la competenza del sindaco sulla salute pubblica.  
> 
> La battaglia è finita?  
> No, ora vorremmo che anche Capri seguisse il nostro esempio. Per vivere davvero su un’isola “deslottizzata”» 

[fonte](http://www.lastampa.it/2016/02/22/italia/cronache/anacapri-il-primo-comune-italiano-senza-slot-ecco-come-abbiamo-sconfitto-lazzardo-oNPo3K7nbYt9ELFFy7dnNN/pagina.html)

[![Licenza CC BY-NC-ND 4.0](https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png)](https://creativecommons.org/licenses/by-nc-nd/4.0/)

**Comment by olistik** [comment]
Iniziativa che ha tratto ispirazione da un [tweet](https://twitter.com/thebrightside0/status/785967120697950209) di [The Bright Side](https://twitter.com/thebrightside0).

**Comment by emilianoferrari1** [comment]
Ciao Maurizio...
Comune di Desio:
RIDUZIONI E AGEVOLAZIONI TARI:
- Bar, caffè, pasticcerie senza slot machine, videolottery terminal, apparecchi con vincite in denaro o similari: tariffa ridotta del 60% sulla quota fissa. 

Nel lontano 2012 il sindaco ha provato a ridurre l'orario... ma purtroppo è finita male:
[Desio. Dopo ricorso al Tar il sindaco sospende ordinanza limiti orario alle slot](http://www.jamma.it/adi/newslot/desio-dopo-ricorso-al-tar-il-sindaco-sospende-ordinanza-limiti-orario-alle-slot-6587)
Ordinanza: http://www.jamma.it/wp-content/uploads/2012/04/ordinanzadesio.pdf 

Nel lontano 2014 invece il comune di Desio vince una causa sulle distanze dei locali con slot:
Ricorso Rofi contro Comune di Desio
http://www.noslot.regione.lombardia.it/cs/Satellite?c=Page&childpagename=DG_Territorio%2FMILayout&cid=1213661330884&p=1213661330884&pagename=DG_TERRWrapper#1213707419430

**Comment by olistik** [comment]
@emilianoferrari1 

> Nel lontano 2014 invece il comune di Desio vince una causa sulle distanze dei locali con slot:
> Ricorso Rofi contro Comune di Desio
> http://www.noslot.regione.lombardia.it/cs/Satellite?c=Page&childpagename=DG_Territorio%2FMILayout&cid=1213661330884&p=1213661330884&pagename=DG_TERRWrapper#1213707419430

Includo qui questo passaggio molto interessante:

> Ricorso Rofi contro Comune di Desio
> Ordinanza Consiglio di Stato, Sezione Quinta, n. 4859 del 22 ottobre 2014
> Nell’ambito del procedimento cautelare instauratosi fra la ROFI S.r.l.s., impresa operante nel settore della raccolta dei giochi pubblici, ed il Comune di Desio (MB), il Consiglio di Stato con ordinanza n. 4859 del 2014 si è pronunciato sulla precedente ordinanza cautelare del TAR di Milano, Sezione Prima, n. 1015 del 24 luglio 2014, respingendo l’appello e conformandosi alla decisione del giudice di primo grado.
> Il contenzioso riguardava l’ordinanza emanata il 19 maggio 2014 dal SUAP del Comune di Desio che disponeva per la ROFI il divieto di installare nei propri locali slot machines e videolotteries, in ossequio a quanto disposto sia dalla l.r. n. 8 del 2013 sia dalla d.g.r. n. 1274 del 2014 in tema di distanze dai luoghi sensibili.
> **Il Consiglio di Stato ha aderito all’interpretazione letterale della normativa regionale resa dal giudice cautelare di primo grado in tema di calcolo della distanza dei 500 metri dai luoghi definiti sensibili**: i termini "raggio" e "baricentro", di cui all’art. 4, comma 2, dell'Allegato A) alla d.g.r. n. 1274 del 2014, vanno intesi nel senso di una misurazione cartografica in linea retta. Qualora il legislatore regionale avesse adottato, di contro, il diverso criterio della distanza pedonale, l’avrebbe indicato espressamente.

È interessante a questo punto considerare che data la lista dei **luoghi sensibili**:
1. istituti scolastici di ogni ordine e grado;
2. luoghi di culto;
3. impianti sportivi;
4. strutture residenziali o semiresidenziali operanti in ambito sanitario o sociosanitario;
5. strutture ricettive per categorie protette;
6. luoghi di aggregazione giovanile;
7. oratori;

[fonte](http://www.noslot.regione.lombardia.it/shared/ccurl/682/1013/distanza_500_metri_luoghi_sensibili_gioco_azzardo_noslot_lombardia.pdf)

ci sarebbe almeno un caso da "raddrizzare":

[![screen shot 2016-10-12 at 16 26 09](https://cloud.githubusercontent.com/assets/21038/19313969/a6abc6d0-9098-11e6-9193-68cd6ced9726.png)](https://www.google.it/maps/place/20832+Desio,+Province+of+Monza+and+Brianza/@45.6173951,9.2081686,3a,75y,320.71h,83.06t/data=!3m7!1e1!3m5!1shtZqmPj2wE1FFhwdjKuV3Q!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3DhtZqmPj2wE1FFhwdjKuV3Q%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D248.47168%26pitch%3D0!7i13312!8i6656!4m5!3m4!1s0x4786bc2374199933:0x40678022e66f550!8m2!3d45.6189486!4d9.198744?hl=en)

Che è praticamente di fronte alla chiesa (e quindi ad un luogo di culto).

Se la situazione è già questa, sarebbe interessante fare qualche calcolo e cominciare a far applicare il regolamento in vigore. :-)

**Comment by olistik** [comment]
@emilianoferrari1 chi contattare ora? ^_^

https://www.comune.desio.mb.it/servizi/menu/dinamica.aspx?idArea=16557&idCat=19603&ID=19603&TipoElemento=categoria

**Comment by emilianoferrari1** [comment]
In realtà è di fianco l'asilo....

**Comment by olistik** [comment]
Jackpot.

**Comment by emilianoferrari1** [comment]
Dovremmo contattare il sindaco che ha deleghe , trasparenza e legalità e commercio 🤔

**Comment by olistik** [comment]
@emilianoferrari1 penso che sarebbe l'interlocutore ideale ma preferirei fare escalation solo se necessario. Ho appena spedito un'e-mail all'URP:

> vorrei sapere se è in vigore un regolamento che vieta l'installazione di slot machines in locali siti a meno di 500m dai luoghi definiti sensibili.
> Maggiori dettagli sul contesto di questa richiesta possono essere
> trovati [qui](https://github.com/open-comune/desio/issues/19)
> E gli specifici riferimenti normativi [qui](https://github.com/open-comune/desio/issues/19#issuecomment-253229036)

**Comment by olistik** [comment]
essendo passata una settimana e non avendo ricevuto alcuna risposta, ho appena spedito un sollecito all'URP:

> vorrei sapere se ci sono aggiornamenti in merito alla mia precedente richiesta.

**Comment by olistik** [comment]
migrata su https://github.com/open-comune/progetta-desio/issues/24

**Comment by lukitto** [comment]
Ragazzi dove la trovo l' ordinanza del sindaco!?
Bello l' esempio di Anacapri ...

**Comment by emilianoferrari1** [comment]
@lukitto 
[ordinanza2012_ Sale Giochi_desio.pdf](https://github.com/open-comune/desio/files/850719/ordinanza2012_.Sale.Giochi_desio.pdf)

**Comment by lukitto** [comment]
Ciao ragazzi si riesce a recuperare 
" Il ricorso contro l'ordinanza firmata dal sindaco Roberto Corti era stato presentato da alcuni commercianti desiani."
http://www.ilcittadinomb.it/stories/Homepage/no-anche-dal-consiglio-di-statodesio-perde-ancora-sulle-slot_1004555_11/?mediaon.trackers.autorefresh.Homepage
Io non la ho trovata .


Stiamo cercando di fare una ITR per capire se l' assessore ha chiesto i dati a rgiole Lombardia per i ludopatici ...

**Comment by lukitto** [comment]
Serve anche l' ordinanza originale del 19.2.2012?
Sapete dove ricuperarla?

**Comment by olistik** [comment]
@lukitto si potrebbe fare una richiesta di accesso civico.
