### ISSUE TITLE
Irregolarità nella votazione ArtBonus

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#2]
- 2016-09-20 14:30: [@olistik](https://twitter.com/olistik) [tweet](https://twitter.com/olistik/status/778209819480166400)

```
- e-mail 1
- data: 2016-09-20 14:34
- da: @olistik
- a: info@retipiu.it
- cc: partecipazione@comune.desio.mb.it

> vi notifico la presenza di questo grave problema di sicurezza nella
gestione della votazione:
> https://twitter.com/olistik/status/778209819480166400
```

```
- e-mail 2
- data: 2016-09-20 17:12
- risposta a: e-mail 1
- da: c.brenna@retipiu.it

> Egregio sig. De Magnis,
> la ringraziamo per la sua gentile segnalazione.
> Il sistema è stato concepito per garantire la massima partecipazione escludendo ulteriori meccanismi di controlli incrociati.
> Ad oggi il sistema impedisce ad ogni votante di votare più volte registrandosi con una medesima email o numero di cellulare.
> Se qualcuno fornisce identità false, ovviamente se assume le relative responsabilità come previsto nel contratto che ogni votante è tenuto a leggere ed accettare.
> Il fatto di partecipare ad un’iniziativa dai fini esclusivamente culturali, dovrebbe essere di per se  incompatibile con comportamenti eticamente scorretti.
> Grazie e cordiali saluti.
```
- 2016-09-21 11:33: [@olistik](https://www.facebook.com/maurizio.demagnis) [FB post](https://www.facebook.com/maurizio.demagnis/posts/10153714770651924)
- 2016-09-21 11:40: [@olistik](https://twitter.com/olistik) [tweet](https://twitter.com/olistik/status/778529355114881024)
- 2016-09-21 14:47: [@olistik](https://twitter.com/olistik) [tweet](https://twitter.com/olistik/status/778576282619617280)
- 2016-09-22 10:48: [@comunedidesio](https://twitter.com/comunedidesio) [tweet](https://twitter.com/comunedidesio/status/778878533867302912)

In attesa di una risposta da Retipiù.

**Comment by olistik** [comment]
- 2016-09-26: [@olistik](https://twitter.com/olistik) [tweet](https://twitter.com/olistik/status/780515488468176896)

> @comunedidesio @RetiPiu_ ancora nessuna risposta?
> Nel frattempo ho notato che sono stati aggiunti due (inefficaci) controlli su CF e e-mail.

**Comment by olistik** [comment]
- 2016-09-26: [@olistik](https://facebook.com/maurizio.demagnis) [FB comment](https://www.facebook.com/groups/823777737638221/permalink/1538331616182826/?comment_id=1538671776148810)

> mi ha fatto notare che è stato aggiunto un controllo sul codice fiscale. Peccato che il sito www.codicefiscale.com permetta di generarne in quantità, compreso quello di "Zio Paperone": PPRZIO80A01D286F.
> 
> Ho infine notato che è stato aggiunto un filtro che rigetta indirizzi e-mail appartenenti a domini come 10minutemail.com e mailinator.com
> Peccato che esistano una caterva di fornitori di indirizzi e-mail gratuiti come GMail, Yahoo che permettono di generare quanti indirizzi e-mail si vuole.
> 
> Ah, ma basta averne anche uno solo, perché se avete un indirizzo gmail come pippo@gmail.com potete usarlo per effettuare quante registrazioni volete dato che pippo+1@gmail.com, pippo+2@gmail.com, ..., pippo+999@gmail.com, etc., rimandano tutti a pippo@gmail.com.

<img width="422" alt="screen shot 2016-09-26 at 23 14 24" src="https://cloud.githubusercontent.com/assets/21038/18852427/a7ab2eae-8440-11e6-8630-ee9e19b64daf.png">

**Comment by olistik** [comment]
- data: 2016-09-22
- url: http://www.retipiu.it/site/content/it/artbonus

pubblicazione sul sito di RetiPiù di una risposta alle richieste di delucidazioni del Comune di Desio

> AVVISO
> 
> Desio, 22 settembre 2016
> 
> La piattaforma di voto fornita a RetiPiù per l'iniziativa "Scegli La Brianza che vuoi" è stata configurata in modo da garantire l'autoregistrazione dei partecipanti, non disponendo di una lista degli “aventi diritto”.
> 
> In maniera auto dichiarativa viene richiesto che ogni votante fornisca il proprio cognome, nome, indirizzo email o numero di cellulare e la dichiarazione di veridicità dei dati forniti.A suo tempo la scelta è sstata quella di non chiedere ulteriori dati personali (CF, indirizzo, ...) agli utenti del sito per favorire  il massimo della partecipazione da parte della cittadinanza. Seppur la piattaforma non consenta in maniera assoluta di poter votare più volte con le medesime generalità, preso atto delle preoccupazioni espresse dall’Amministrazione Comunale di Desio di un possibile utilizzo fraudolento della piattaforma di voto, abbiamo deciso di integrare le procedure di registrazione richiedendo ai partecipanti di inserire obbligatoriamente il proprio Codice Fiscale per poter ottenere le credenziali di voto. 
> 
> Il Codice fiscale è richiesto ai soli fini di autenticazione per il voto. In ogni caso il sistema garantisce l'assoluta segretezza ed anonimato del voto, a garanzia dei diritti di privacy dei cittadini.
> 
> Cogliamo l’occasione per ringraziare anticipatamente tutti i cittadini che vorranno partecipare a questa iniziativa, cogliendone appieno le finalità di sensibilizzazione rispetto alle necessità di tutelare e valorizzare il nostro patrimonio culturale.

**Comment by olistik** [comment]
- data: 2016-09-28

Commissione del Comune di Desio per decidere come reagire alla risposta di RetiPiù.

**Inserire un documento ufficiale**

**Comment by olistik** [comment]
- data: 2016-09-29 17:48
- [commento Facebook](https://www.facebook.com/groups/823777737638221/permalink/1538331616182826/?comment_id=1541711742511480&comment_tracking=%7B%22tn%22%3A%22R%22%7D) di [Achille Taccagni](https://www.facebook.com/akitac)

> Maurizio De Magnis, sai come la penso. Trovo ridicolo il sistema costruito da RetiPiù e ancor peggiore la loro risposta alle nostre richieste di chiarimento (trovate la risposta in apertura della pagina di voto, http://www.retipiu.it/site/content/it/artbonus). Ritengo però che al momento l'idea di sfilarsi dal progetto sia irragionevole. È improbabile infatti che una nostra presa di posizione in tal senso possa convincere Retipiù a rivedere il sistema: primo, perché la risposta che finora abbiamo ricevuto è, a mio parere, un semplice contentino che non denota particolare interesse per la questione; secondo, come il loro comunicato ben sottolinea, perché siamo stati gli unici, fra tutti i soggetti partecipanti, a prendere posizione in merito al sistema di voto e a lamentarcene con loro. Dall'altra parte, so bene che sarebbe assurdo se dopo averne fatto un punto di legalità, ci accontentassimo della modifica fatta, che chiaramente non può dirci soddisfatti. Per questo sono convinto che il comune debba muoversi in due direzioni: da una parte, continuare il pressing su RetiPiù perché renda il sistema il più invulnerabile possibile, provando anche a coinvolgere gli altri partecipanti nell'obiettivo; dall'altra, mobilitare la popolazione al voto, per cercare comunque, e onestamente, di trarne vantaggio. E credo che non si possa proprio parlare di disonestà o di immobilismo dell'amministrazione, proprio alla luce del fatto, come dicevo, che finora è stata l'unica a muoversi per far notare il problema.
> Sulla commissione di ieri sera: non è ancora disponibile il verbale (la riunione era però aperta al pubblico), ma posso comunque ricordare senza troppi sforzi che nessuno, di nessuna area politica, ha aperto la discussione sulla questione della sicurezza del voto. L'Assessore Redi ha esposto il progetto, ha ricordato la richiesta di chiarimenti effettuata dal Comune e e ha letto la risposta di RetiPiù, al che la discussione è stata incentrata esclusivamente sulle strategie di comunicazione per mobilitare i desiani al voto. Io ho letto ciò come il desiderio condiviso di non lasciarsi sfuggire un'occasione simile, probabilmente irripetibile, per poter accedere ai fondi necessari ad un progetto che sta a cuore a tutta la cittadinanza. E questo desiderio, come dicevo, non è secondo me assolutamente incoerente con la battaglia di legalità che si continuerà a fare sul punto.

**Comment by olistik** [comment]
- data: 2016-09-29 18:07
- risposta a [questo](https://github.com/open-comune/desio/issues/2#issuecomment-250687327) messaggio
- autore: [Maurizio De Magnis](https://www.facebook.com/maurizio.demagnis)
- [fonte](https://www.facebook.com/groups/823777737638221/permalink/1538331616182826/?comment_id=1541711742511480&reply_comment_id=1541731802509474&comment_tracking=%7B%22tn%22%3A%22R9%22%7D)

> grazie davvero per la risposta :-)
> 
> Oltre alla pessima (eufemismo) gestione della comunicazione di Retipiù, l'enorme pubblicità scontata da loro ottenuta tramite il fondo Art Bonus (che, ricordiamo, dovrebbe avere scopi ben più virtuosi della mera marchetta) è per me condizione sufficiente per annullare ogni beneficio del dubbio sulla loro presunta ingenuità.
> 
> Hanno colto un'occasione per farsi pubblicità scontata.
> 
> Detto questo, i fatti ora sono che chiunque abbia un minimo di interesse nel falsare il voto (e sono in tanti) lo potrà fare.
> E dati questi presupposti, la probabilità che lo farà sarà alta, talmente alta da rendere ogni ipotesi di "onestà" e conseguentemente ogni incitazione allo "sfruttare l'occasione" quantomeno naive.
> 
> Secondo me sarebbe meglio che Retipiù decidesse autonomamente la rosa dei tre progetti più meritevoli, facendosi quindi carico di giustificare nei confronti di Art Bonus questa scelta (troppo comodo usare l'etichetta della scelta partecipativa per lavarsi le mani di eventuali controlli). Non stiamo parlando di miliardi di €, è vero, ma ricordiamoci quanto qualunque Comune sarebbe propenso a elargire con la stessa superficialità € 100.000.
> 
> Se non ricordo male il bilancio partecipativo di Desio si è basato proprio sull'autenticazione forte, per assicurarsi che la scelta rappresentasse la volontà dei cittadini.
> 
> Questo si chiama in gergo tecnico "to give a fuck" ed è ammirevole.
> 
> P.S.: non credo che l'amministrazione possa essere tacciata di disonestà e immobilismo.

**Comment by olistik** [comment]
Organigramma struttura societaria AEB (Ambiente Energia Brianza) / Gelsia

![organigramma_struttura_societaria](https://cloud.githubusercontent.com/assets/21038/18991344/45ca25ca-8718-11e6-84ad-0b7c10da2339.png)

[fonte](http://www.aebonline.it/ambiente-energia-brianza/struttura-societaria-0000126.html)
[segnalazione](https://www.facebook.com/groups/823777737638221/permalink/1538331616182826/?comment_id=1541711742511480&reply_comment_id=1542076915808296&comment_tracking=%7B%22tn%22%3A%22R9%22%7D)

**Comment by olistik** [comment]
Con pessimismo, chiudo la issue.

**Comment by olistik** [comment]
[RISULTATO.pdf](https://github.com/open-comune/desio/files/567888/RISULTATO.pdf)

**Comment by emilianoferrari1** [comment]
Però da sito mi sembra un bel comune organizzato... http://www.comune.cabiate.co.it/ 
Inoltre "Cambiate Cabiate con Noi" ha preso quasi 1700 voti quando le votazioni di reti + hanno votato in 1200 ... (http://www.comune.cabiate.co.it/public/B313/documenti/2752014144617331.pdf) , niente male!!

**Comment by olistik** [comment]
@emilianoferrari1 non posso infatti dire che ci siano prove inconfutabili di un comportamento scorretto. Servirebbe avere maggiori informazioni sui risultati della votazione per capire se sono state votazioni falsate o meno.
Servirebbe un ente terzo certificatore ma suppongo che questa attività non interessi a chi può richiederla.

**Comment by emilianoferrari1** [comment]
Si si ... anch'io rimango dell'opinione che una cosa del genere non è accettabile.
Siccome io sono fiducioso... la mia osservazione si sposta sul fatto che la giunta ha avuto un bel ritorno anche in queste votazioni, non solo nel periodo elettorare... Con questa votazione di Reti + la legge dei grandi numeri ha completamente fallito...
Sarebbe interessante seguirne anche i passi sucessivi... ;-)
