### ISSUE TITLE
Mappatura degli immobili pubblici non utilizzati

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#20]
## Attività
- [ ] richiedere informazioni al Comune

**Comment by olistik** [comment]
Blocca #9

**Comment by olistik** [comment]
Richiesta spedita all'URP e all'assessore Rocco:

> vorrei chiedervi supporto per la realizzazione di un progetto di mappatura degli immobili pubblici inutilizzati.
> 
> Gli scopi di questo progetto sono:
> - rendere maggiormente accessibili le suddette informazioni, usando lo stato dell'arte delle tecnologie digitali (repository GitHub)
> - abilitare proposte di progetti che riguardano gli immobili pubblici [1] [2]
> 
> Questa proposta è stata inserita nel contenitore http://open.desio.org [3]
> 
> Resto a vostra disposizione,
> Maurizio
> 
> [1] https://github.com/open-comune/desio/issues/9
> [2] https://github.com/open-comune/desio/issues/21
> [3] https://github.com/open-comune/desio/issues/9

**Comment by olistik** [comment]
Segnalato da @Saram0n : http://www.comune.desio.mb.it/servizi/menu/dinamica.aspx?ID=34308&bo=true

**Comment by ipersoft** [comment]
https://github.com/comune-desio/opendata/blob/master/immobili-comunali__fabbricati--2016-02-26.csv

https://github.com/comune-desio/opendata/blob/master/immobili-comunali__terreni--2016-02-26.csv

**Comment by olistik** [comment]
@ipersoft thx! Mi ero dimenticato che l'aveva caricato @favoeva e che l'ho successivamente modificato :-)
Gli immobili non utilizzati dovrebbero essere un sottoinsieme di questi due documenti.
Intanto provo ad ottenere le coordinate GPS di questi record e a metterli in una mappa.

**Comment by ipersoft** [comment]
;-)

**Comment by olistik** [comment]
Allego la nuova posizione dei dataset:

https://github.com/comune-desio/opendata/tree/master/immobili-comunali

e il lavoro di visualizzazione svolto da @ipersoft per terreni e fabbricati:

- https://www.infocitta.info/terreni/
- https://www.infocitta.info/fabbricati/

**Comment by olistik** [comment]
migrata su https://github.com/open-comune/progetta-desio/issues/25
