### ISSUE TITLE
Uso condiviso, da parte di associazioni, di un immobile pubblico inutilizzato

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#21]
Dipendente da #20 
## Premessa

Ispirato dal commento di @emilianoferrari1 https://github.com/open-comune/desio/issues/9#issuecomment-252177080
## Descrizione

> un mio vicino, nonché facente parte della social Street è un appassionato di giochi in scatola e sull'esempio di altri paesi, mi aveva chiesto di incontrare l'assessore alla cultura perché voleva proporgli di aprire un' associazione della "Tana dei Goblin" ( rif. http://www.goblins.net/basic-page/chi-siamo).
> L'idea era quella di avere uno spazio condiviso, in cui le associazioni , potessero regolarsi in autonomia nei tempi voluti [..]
> 
> Inoltre ci sono degli edifici , del vecchio ospedale, di fronte alla piazza don Giussani che sono totalmente vuoti ed inutilizzati. Oltre che ulteriori edifici/case confiscate alla mafia, vedi allegato.

![Articolo](https://cloud.githubusercontent.com/assets/17992225/19182640/9a5a674c-8c74-11e6-83a5-80acf81e1a7b.png)
## Attività
- [x] richiedere un confronto con il Comune riguardo alle possibilità

**Comment by olistik** [comment]
@emilianoferrari1 pensi sia necessario fornire informazioni più dettagliate riguardo alla proposta?

**Comment by emilianoferrari1** [comment]
Già fatto con l'assessore Redi. Credo stia aspettando la disponibilità dell'ufficio partecipazione. Al momento, nessun risposta.

**Email**:
Fwd: Richiesta di apertura spazio ricreativo
Emiliano Ferrari 

12 set

a assessoreredi, partecipazione
Buon giorno Cristina,
   mi scuso per il disturbo, ma vorrei arrivare a un dunque con questa richiesta secondo me valida, sia dal punto di vista della partecipazione cittadina, che di visibilità dell'assessorato alla cultura ed alla partecipazione.

Come suggeritomi, ho anticipato i tempi chiedendo al Sig. Cottini, come possa rendersi disponibile al momento uno spazio condiviso, in che tempi e in che luoghi...anche itinerante . In settimana si è ripromesso di farmi sapere.

La richiesta del sig. E, che prenderebbe in carico tutta l'organizzazione è quella di incontrarti o incontrarvi, in orario di ufficio, per spiegarvi il suo progetto.

Qualche riga e riferimento ve lo avevo già mandato nell'email quì sotto, di cui però non ho avuto alcun riscontro.
Se fosse possibile ottenere una risposta in settimana, sarebbe magnifico.
Grazie 1000 per la disponibilità,
Spero di sentirci presto.
Buona giornata,

Emiliano

---------- Messaggio inoltrato ----------
Da: Emiliano Ferrari 
Date: 27 giugno 2016 17:04
Oggetto: Richiesta di apertura spazio ricreativo
A: partecipazione Comune di Desio partecipazione@comune.desio.mb.it
Cc: assessoreredi@comune.desio.mb.it

Buon giorno Malù, Assessore Redi,

vorrei mettermi in contatto con voi per una richiesta che mi è pervenuta riguardo la possibilità di aprire in Desio la prima associazione della Brianza della Tana dei Goblin.

Forse avrete un bel sorriso come quello che ho fatto io appena mi è stato detto, infatti sono molti i giocatori di giochi in scatola che per motivi di incomprensione non hanno uno spazio a disposizione, ma sentite qui:

1.Permette a persone adulte di avvicinarsi al gioco intelligente: senza scopo di lucro o d’azzardo.
1. Contribuisce a Manifestazioni di carattere Nazionale: ModCon/Play, Lucca Comics & Games, Comicon, Ludica, Pisacon…
2. Promuove attività interne di aggregazione, sponsorizzando l’attività torneistica. I TdG Italian Masters, si tengono da più di dieci anni e partecipano agli European Boardgames Championship.
3. Inoltre, organizza giornate di gioco e week-end ludici, con il supporto e la collaborazione di operatori locali (agriturismi, hotel, ecc) ed a cui tutti possono partecipare gratuitamente.
4. Con più di 18000 utenti registrati e migliaia di forum di discussione, è uno dei “contenitori” ludici principali in Italia

Qui, per maggiori dettagli: http://www.goblins.net/

Quello che mi ha chiesto questo amico e la possibilità di avere un posto a titolo gratuito per poter fondare una affiliata di questa associazione.

Possiamo sentirci ed incontrarci?

Grazie 1000,

A tutti

Buona continuazione.

Emiliano

**Comment by olistik** [comment]
@emilianoferrari1 sono abbastanza interessato a seguire questa attività anche perché potrebbe aiutare #20 :-)

**Comment by olistik** [comment]
@emilianoferrari1 ancora nessuna news?
Possiamo mandare un sollecito?

**Comment by emilianoferrari1** [comment]
Secondo me sarebbe meglio aspettare settimana prossima, al momento so che manca del personale... 
Grazie ;-)

**Comment by olistik** [comment]
Aggiungo il riferimento dell'[Università Europea degli Sport della Mente](http://www.uniesm.it/chi-siamo/)
Qualche aggiornamento ricevuto?

**Comment by emilianoferrari1** [comment]
Non capisco la non risposta....
Maurizio ci stai ? 
L'assessore Redi, riceve il mercoledì dalle 10 alle 12 su appuntamento, telefonando allo 0362 392.235 
Provo a sentire anche il mio vicino interessato, che non usa questo mezzo, per sapere se è libero il Mercoledì.
Ok?

**Comment by olistik** [comment]
@emilianoferrari1 potremmo provare a fissare un appuntamento per settimana prossima.

**Comment by emilianoferrari1** [comment]
Il 24/11, ricevuti all'appuntamento alcuni degli interessati ad aprire l'associazione "Tana dei Goblin" .
Devo ancora chiedere info...

**Comment by olistik** [comment]
migrata su https://github.com/open-comune/progetta-desio/issues/26
