### ISSUE TITLE
creazione di una Wiki riguardante l'inceneritore di Desio

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#23]
http://gianmarcocorbetta.it/?s=inceneritore+desio

Ammetto di trovarmi un po' disorientato dalla quantità d'informazioni presenti.

Nel blog di Gianmarco Corbetta le informazioni sono mostrate in forma di Blog (ok, tautologia) ovvero articoli praticamente indipendenti tra di loro, mostrati in ordine cronologico inverso.

Questo significa che alcune informazioni rilevanti scritte nei post più vecchi non sono direttamente accessibili nonostante possano risultare ancora rilevanti.

È una forma comunicativa utile per trasmettere notizie ma non sostituisce una base di conoscenza strutturata come lo sarebbe invece una Wiki. Il Blog potrebbe anzi essere uno strumento che evidenzia nuovi sviluppi legati ad un Wiki.

In una Wiki le informazioni contenute non perdono di visibilità nel corso del tempo perché a partire dall'entità "inceneritore di Desio" (rappresentante una struttura fisica dotata di una posizione geografica), sono presenti tutte le relazioni/fatti che la riguardano e per ognuno di questi fatti il gioco si ripete, permettendo così una navigazione efficiente delle informazioni.

Il vantaggio di questa forma di documentazione, rispetto al Blog, è che è aggiornabile da più persone in maniera collaborativa. Non c'è quindi un "singolo punto di fallimento" (mettiamo caso che Gianmarco non possa/voglia più preoccuparsi dell'argomento) e i naturali controlli incrociati della pluralità di individui che partecipano alla sua gestione evita che le informazioni presenti siano viziate dagli eventuali pregiudizi personali.

**Comment by emilianoferrari1** [comment]
Qui potrebbero entrare in causa anche i comitati di Quartiere, sopratutto Il CdQ di San Giovanni Battista . Dimmi cosa serve per coinvolgerli... THK

**Comment by olistik** [comment]
@emilianoferrari1 alla grande :-)

La soluzione migliore per partire potrebbe essere di partire dall'inserire le informazioni sui **fatti** all'interno di questa pagina wiki: https://github.com/open-comune/desio/wiki/Inceneritore

Dovremmo cercare di limitarci ai soli fatti, inserendo documenti e riferimenti ufficiali.

Qualora una sola pagina non dovesse bastare, potremmo creare altre pagine o anche semplicemente spostare il materiale in un repository a parte.

Chiunque sia intenzionato a contribuire può creare un account GitHub e notificarmi il suo nome utente, in modo da aggiungerlo tra gli utenti che possono modificare la wiki.

**Comment by olistik** [comment]
migrato a https://github.com/open-comune/progetta-desio/issues/27
