### ISSUE TITLE
Predisposizione di una piattaforma di Whistleblowing (GlobaLeaks)

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#26]
http://globaleaks.org/

**Comment by olistik** [comment]
https://www.transparency.it/linee-guida-per-la-predisposizione-di-procedure-in-materia-di-whistleblowing/

**Comment by emilianoferrari1** [comment]
http://unb.lattecreative.com/tl.php?p=1dv/1cq/rs/fmc5/sa/rs//https%3A%2F%2Fwww.riparteilfuturo.it%2Fwhistleblower-italia%3Futm_source%3Demail%26utm_medium%3DRIF_2016_11_29%26utm_campaign%3DNL%26link%3Dbutton

**Comment by emilianoferrari1** [comment]
I membri della Commissione Affari Costituzionali del Senato hanno tempo fino al 14 dicembre per presentare emendamenti alla proposta di legge sul whistleblowing. In momenti come questo dobbiamo fare sentire la nostra voce per far capire ai politici l’urgenza di questa legge: un vero e proprio scudo per chi decide di denunciare la corruzione, rischiando intimidazioni, mobbing e a volte la carriera.
https://www.riparteilfuturo.it/whistleblower-italia?utm_source=email&utm_medium=RIF_2016_11_29&utm_campaign=NL&link=button

**Comment by olistik** [comment]
migrato a https://github.com/open-comune/progetta-desio/issues/30
