### ISSUE TITLE
Bando Cariplo #comunitaresilienti

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#39]
> Emiliano Ferrari:
> Ciao a tutti,
> vi ricordo che nell’aprile di quest’anno sono stato chiamato per "sostenere" il comune di Desio e Agenda21, insieme a diverse altre realtà associative, al bando #Comunitàresilienti di Cariplo.

[fc_16ambcomunita_web.pdf](https://github.com/open-comune/desio/files/590301/fc_16ambcomunita_web.pdf)

> http://www.fondazionecariplo.it/static/upload/fc_/fc_16ambcomunita_web.pdf
>  
> Bene…il bando sarà finanziato!!🎉
> Ora mi aspetto che sulla pagina del comune di Desio appaia presto qualche informazione in più e si possano seguire tutti gli sviluppi che porteranno a nuove ciclabili, al recupero di aree abbandonate ai rifiuti ecc..
> 
> Questi sono alcuni punti su come è stato sviluppato il progetto:
> 
> 1. Vigilare il territorio: facilitazione nella segnalazione di problematiche collegate al verde pubblico cittadino, soprattutto connesso alle piccole e grandi discariche abusive sul territorio
> 2. Curare il territorio: azione volta alla “cura” del territorio, riguardante il potenziamento del servizio dei volontari del verde e la possibilità di manutenzione delle aree verdi da parte di associazioni e comitati
> 3. Vivere il territorio: azione di “adozione” di alcune aree verdi strategiche da parte di associazioni/comitati
> 4. Spostarsi nel territorio: recupero delle strade vicinali per favorire lo spostamento ciclopedonale in città

**Comment by emilianoferrari1** [comment]
[lettera sostegno_residenti Via Milano.pdf](https://github.com/open-comune/desio/files/591426/lettera.sostegno_residenti.Via.Milano.pdf)
[quadro-logico_CURARE DESIO.PDF](https://github.com/open-comune/desio/files/591427/quadro-logico_CURARE.DESIO.PDF)
[progetto Curare Desio.pdf](https://github.com/open-comune/desio/files/591428/progetto.Curare.Desio.pdf)

**Comment by emilianoferrari1** [comment]
NEWS!!

Carissime associazioni di Desio, 


come vi avevo già anticipato sul finire del 2016, Fondazione Cariplo ha sostenuto con un contributo il progetto CURARE DESIO, che Agenzia InnovA21 e Comune di Desio hanno presentato al bando Comunità Resilienti - 2016.

Come ricorderete, il progetto nasce dalla condivisione di obiettivi e azioni con il territorio: dai numerosi incontri di partecipazione messi in atto in questi anni dal Comune e gestiti da InnovA21 e, soprattutto, dalla condivisione con voi durante gli incontri di pre-progetto.


Dopo una prima fase di adempimenti amministrativi e organizzazione interna, siamo pronti a partire con le attività e il coinvolgimento degli attori locali!


A tale proposito, Agenzia e Comune di Desio hanno il piacere di invitarvi al primo incontro di scambio e progettazione del progetto che si terrà
•sabato 18 marzo
•ore 10.00
•presso Villa Tittoni - DesioLab (ala ovest - NB: entrando dal cancello della Villa dovete entrare nella porta sulla destra) 



Vi aspettiamo numerosi!

Come sempre, rimango disponibile per qualsiasi approfondimento.

Grazie e a presto

Simone

**Comment by olistik** [comment]
@emilianoferrari1 penso sia il caso di chiudere questa issue e di crearne un'altra specifica per Curare Desio su http://progetta.desio.org
Che ne dici?

**Comment by emilianoferrari1** [comment]
Buona idea ! 😁✌🏻
Il giorno ven 10 mar 2017 alle 16:59 Maurizio De Magnis <
notifications@github.com> ha scritto:
