### ISSUE TITLE
Accesso libero a Internet

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#6]
Data la complessità del progetto è stato creato uno spazio a parte: http://internet.desio.org

**Comment by emilianoferrari1** [comment]
Non ho capito come inserire una proposta nello spazio a parte, comunque era interessante l'utilizzo della Premobox con un aspetto anche all'ambiente circostante... vedi: http://www.wired.it/internet/web/2016/07/12/amsterdam-wi-fi-libero-se-aria-pulita/

Ciao ;-)

**Comment by olistik** [comment]
@emilianoferrari1 

> Non ho capito come inserire una proposta nello spazio a parte,

Ti ho aggiunto come membro del gruppo che può accedere in scrittura al repository https://github.com/open-comune/desio--internet
Ora puoi aggiungere una proposta o commentarne una pre-esistente.

> comunque era interessante l'utilizzo della Premobox con un aspetto anche all'ambiente  circostante... vedi: http://www.wired.it/internet/web/2016/07/12/amsterdam-wi-fi-libero-se-aria-pulita/

Pur vedendo la pagina ufficiale http://treewifi.org/ non riesco a vedere i dettagli tecnici della soluzione, che ad ora è solo pre-ordinabile. Prima ancora di comprendere importanti dettagli come:
- copertura geografica
- gestione dell'utenza
- suddivisione equa della banda a disposizione tra gli utenti connessi

è critico capire quale sia il metodo usato per accedere ad Internet.

Penso che nonostante manchino ancora questi dettagli sia un ottimo candidato per una proposta indipendente :-)
Una delle prime attività sarebbe proprio contattare gli autori e chiedere le informazioni tecniche sopra menzionate.

**Comment by emilianoferrari1** [comment]
Forse Premoli, potrebbe essere interessato ad implementare il suo progetto... certo dovremmo poter parlare con il Sindaco per sapere se vogliono investire qualcosa....

**Comment by olistik** [comment]
migrato su https://github.com/open-comune/progetta-desio/issues/15
