### ISSUE TITLE
utilizzo di un immobile pubblico inutilizzato per corsi e coworking

### ISSUE THREAD

**Issue by olistik** [open-comune/desio#9]
## Scopo

Dipende da #20 

**Un [Talent Garden](http://milano-merano.talentgarden.org/) dal taglio sociale a Desio.**

Prendendo ispirazione da un articolo ([link](https://www.facebook.com/cristina.redi.1/posts/1762868830629871)) si vuole creare uno spazio dove:
1. poter erogare un'offerta corsi/workshop simile a quella di Hubout Makers ([link](https://github.com/hubout-makers/corsi))
2. offrire un ambiente di coworking, con particolare riferimento a:
   1. disoccupati
   2. chi sta seguendo un percorso di formazione professionale
   3. liberi professionisti

Il servizio di coworking avrebbe un costo differente in base all'utenza (vedi il precedente punto 2.)
## Attività
- [ ] verificare preliminare fattibilità con Comune e Hubout Makers
- [ ] identificare gli scopi possibili/voluti per un immobile inutilizzo
- [ ] identificare gli immobili pubblici (comunali?) attualmente inutilizzati
- [ ] per ogni immobile trovato effettuare una preliminare stima dei costi necessari per la messa l'utilizzo dell'immobile (imbiancatura, mobilia, apparecchiature elettroniche, allacciamento ad Internet)
- [ ] identificare l'immobile più adatto
- [ ] TBD

**Comment by emilianoferrari1** [comment]
Ciao Maurizio,
un mio vicino, nonché facente parte della social Street è un appassionato di giochi in scatola e sull'esempio di altri paesi, mi aveva chiesto di incontrare l'assessore alla cultura perché voleva proporgli di aprire un' associazione della "Tana dei Goblin" ( rif. http://www.goblins.net/basic-page/chi-siamo).
L'idea era quella di avere uno spazio condiviso, in cui le associazioni , potessero regolarsi in autonomia nei tempi voluti: forse centra qualcosa con la tua idea?

Inoltre ci sono degli edifici , del vecchio ospedale, di fronte alla piazza don Giussani che sono totalmente vuoti ed inutilizzati. Oltre che ulteriori edifici/case confiscate alla mafia, vedi allegato.
![beni confiscati](https://cloud.githubusercontent.com/assets/17992225/19182640/9a5a674c-8c74-11e6-83a5-80acf81e1a7b.png)

Ciao,
Fammi sapere cosa ne pensi!
Emiliano

**Comment by olistik** [comment]
@emilianoferrari1 interessante, penso che una una buona soluzione sia:
1. estraiamo da questa issue un mini progetto di mappatura degli immobili inutilizzati
2. questa issue diventa dipendente dalla mappatura degli immobili
3. apriamo un'altra issue, anch'essa dipendente dalla mappatura degli immobili, in cui la destinazione possibile è proprio uno spazio condiviso in cui le associazioni possano regolarsi in autonomia

Piace?

**Comment by emilianoferrari1** [comment]
Come si Fa?

**Comment by olistik** [comment]
@emilianoferrari1 ^^ così :-D

A questo punto faccio partire anche questa richiesta.

**Comment by olistik** [comment]
Richiesta spedita all'ufficio Partecipazione, mettendo in copia il Sindaco, gli assessori Redi e Borgonovo, Matteo Bonanno di Hubout Makers Lab e Davide Scorza di HubDesio.

> mi chiamo Maurizio De Magnis e vorrei proporvi di realizzare una soluzione in stile Talent Garden [0], dal taglio sociale a Desio.
> 
> Prendendo ispirazione da un articolo [1] vorrei creare uno spazio dove:
> 1. poter erogare un'offerta corsi/workshop simile a quella di Hubout Makers [2]
> 2. offrire un ambiente di coworking, con particolare riferimento a:
>    i. disoccupati
>    ii. chi sta seguendo un percorso di formazione professionale
>    iii. liberi professionisti
> 
> Il servizio di coworking avrebbe un costo differente in base all'utenza (vedi il precedente punto 2.)
> 
> Vorrei quindi verificare con voi la fattibilità e la volontà di realizzare questo obiettivo, identificando l'immobile adeguato e modulando in maniera ottimale le modalità di erogazione del servizio.
> 
> Metto in copia anche Matteo Bonanno di HuboutMakers Lab e Davide Scorza di HubDesio, che potrebbero eventualmente risultare interlocutori interessati al progetto.
> 
> Resto a vostra disposizione,
> Maurizio
> 
> [0] http://milano-merano.talentgarden.org
> [1] https://www.facebook.com/cristina.redi.1/posts/1762868830629871
> [2] https://github.com/hubout-makers/corsi

**Comment by olistik** [comment]
migrato su https://github.com/open-comune/progetta-desio/issues/18
